"""empty message

Revision ID: 42a037209c30
Revises: 
Create Date: 2019-09-25 15:04:44.427380

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '42a037209c30'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('channels',
    sa.Column('channel_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=140), nullable=False),
    sa.Column('username', sa.String(length=30), nullable=False),
    sa.Column('admin', sa.String(length=32), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('is_running', sa.Boolean(), nullable=True),
    sa.Column('due_date', sa.DateTime(), nullable=True),
    sa.Column('has_infinite_subsribe', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('channel_id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('inviters',
    sa.Column('inviter_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('inviter_id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('channelInviters',
    sa.Column('inviter_id', sa.BigInteger(), nullable=False),
    sa.Column('channel_id', sa.BigInteger(), nullable=False),
    sa.Column('code', sa.String(length=60), nullable=False),
    sa.ForeignKeyConstraint(['channel_id'], ['channels.channel_id'], ),
    sa.ForeignKeyConstraint(['inviter_id'], ['inviters.inviter_id'], ),
    sa.PrimaryKeyConstraint('inviter_id', 'channel_id', 'code'),
    sa.UniqueConstraint('code')
    )
    op.create_table('referrals',
    sa.Column('inviter_id', sa.BigInteger(), nullable=False),
    sa.Column('channel_id', sa.BigInteger(), nullable=False),
    sa.Column('receiver_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['channel_id'], ['channels.channel_id'], ),
    sa.ForeignKeyConstraint(['inviter_id'], ['inviters.inviter_id'], ),
    sa.PrimaryKeyConstraint('channel_id', 'receiver_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('referrals')
    op.drop_table('channelInviters')
    op.drop_table('inviters')
    op.drop_table('channels')
    # ### end Alembic commands ###
