"""empty message

Revision ID: ffb263f0b87c
Revises: 42a037209c30
Create Date: 2019-10-05 05:05:23.552827

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ffb263f0b87c'
down_revision = '42a037209c30'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('channels', sa.Column('admin_id', sa.BigInteger(), nullable=False))
    op.drop_column('channels', 'admin')
    op.add_column('inviters', sa.Column('first_name', sa.String(), nullable=True))
    op.add_column('inviters', sa.Column('last_name', sa.String(), nullable=True))
    op.alter_column('inviters', 'name',
               existing_type=sa.VARCHAR(length=32),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('inviters', 'name',
               existing_type=sa.VARCHAR(length=32),
               nullable=False)
    op.drop_column('inviters', 'last_name')
    op.drop_column('inviters', 'first_name')
    op.add_column('channels', sa.Column('admin', sa.VARCHAR(length=32), autoincrement=False, nullable=False))
    op.drop_column('channels', 'admin_id')
    # ### end Alembic commands ###
